// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cloud.google.com/go/firestore"
	"github.com/vinodhalaharvi/grpc-web-template/gen/go"
	"github.com/vinodhalaharvi/grpc-web-template/gen/go/servers"
)

// Injectors from wire.go:

func InitializeServer(client *firestore.Client, cfg *purecertsv1.ServerConfig) (*Server, error) {
	serveMux := purecertsv1.NewServerMux()
	server := purecertsv1.NewHTTPServer(serveMux, cfg)
	firestoreInviteRepository := purecertsv1.NewFirestoreInviteRepository(client)
	firestoreUserRepository := purecertsv1.NewFirestoreUserRepository(client)
	firestoreTenantRepository := purecertsv1.NewFirestoreTenantRepository(client)
	firestoreCertificateRepository := purecertsv1.NewFirestoreCertificateRepository(client)
	firestoreCARepository := purecertsv1.NewFirestoreCARepository(client)
	firestoreAuditLogRepository := purecertsv1.NewFirestoreAuditLogRepository(client)
	firestoreSessionRepository := purecertsv1.NewFirestoreSessionRepository(client)
	firestoreAPIKeyRepository := purecertsv1.NewFirestoreAPIKeyRepository(client)
	firestoreSubscriptionRepository := purecertsv1.NewFirestoreSubscriptionRepository(client)
	firestorePlanRepository := purecertsv1.NewFirestorePlanRepository(client)
	firestoreInvoiceRepository := purecertsv1.NewFirestoreInvoiceRepository(client)
	repositories := purecertsv1.NewRepositories(firestoreInviteRepository, firestoreUserRepository, firestoreTenantRepository, firestoreCertificateRepository, firestoreCARepository, firestoreAuditLogRepository, firestoreSessionRepository, firestoreAPIKeyRepository, firestoreSubscriptionRepository, firestorePlanRepository, firestoreInvoiceRepository)
	billingServiceServer := servers.NewBillingServiceServer(repositories)
	userServiceServer := servers.NewUserServiceServer(repositories)
	tenantServiceServer := servers.NewTenantServiceServer(repositories)
	certificateServiceServer := servers.NewCertificateServiceServer(repositories)
	caServiceServer := servers.NewCAServiceServer(repositories)
	auditServiceServer := servers.NewAuditServiceServer(repositories)
	sessionServiceServer := servers.NewSessionServiceServer(repositories)
	apiKeyServiceServer := servers.NewAPIKeyServiceServer(repositories)
	mainServer := NewServer(serveMux, server, billingServiceServer, userServiceServer, tenantServiceServer, certificateServiceServer, caServiceServer, auditServiceServer, sessionServiceServer, apiKeyServiceServer)
	return mainServer, nil
}
